-- AGREGANDO UNA LLAVE PRIMARIA Y AGREGANDO UNA COLUNMA A UNA TABLA

ALTER TABLE TBClientes ADD PRIMARY KEY(DNI);
ALTER TABLE TBClientes ADD COLUMN(FECHA_NACIMIENTO DATE);

-- AGREGANDO UN REGISTRO A LA TABLA CON LA NUEVA COLUMNA
INSERT INTO TBClientes(
DNI,
NOMBRE,
DIRECCION1,
DIRECTCION2,
BARRIO,
CIUDAD,
ESTADO,
CP,
EDAD,
SEXO,
LIMITE_CREDITO,	
VOLUMEN_COMPRA,
PRIMERA_COMPRA,
FECHA_NACIMIENTO) VALUES (
'456879548', 'Pedro El Escamaso', 'Calle del Sol, 25', '', 'Los Laureles', 'Ciudad de Mexico', 'Mexico', '65784', 50, 'M', 1000000, 2000, 0, '1973-01-25'
);

select * from TBClientes;